version: "3.7"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./db/schema_queries/:/opt/schema_queries/
      - psql_database:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  psql_database:
    name: psql_database